
# Args: I think there were problems with trailing spaces at end of line. 2020-08-18_Tue_14.08-PM


# dockerfile..  https://github.com/elastic/dockerfiles/tree/v7.8.1/logstash

ARG ELK_VERSION 

#FROM docker.elastic.co/logstash/logstash:6.4.0

FROM logstash:"${ELK_VERSION}"


# having some difficulty passing env var to dockerfile. Trying things..
RUN echo "$ELK_VERSION"
RUN echo "${MYSQL_CONNECT_VER}"
RUN echo $MYSQL_CONNECT_VER

USER 0

RUN cat /etc/lsb-release || cat /etc/centos-release

RUN yum update -y && yum install -y wget && \
    yum clean all

USER 1000

#安装input插件
# RUN /usr/share/logstash/bin/logstash-plugin install logstash-input-jdbc


#安装filter插件
#RUN /usr/share/logstash/bin/logstash-plugin install logstash-filter-aggregate
#RUN /usr/share/logstash/bin/logstash-plugin install logstash-filter-jdbc_streaming
#RUN /usr/share/logstash/bin/logstash-plugin install logstash-filter-mutate


#安装output插件
RUN logstash-plugin install logstash-output-elasticsearch


# COPY ./mysql-connector-java-5.1.46.jar /usr/share/logstash/mysql-connector-java.jar
#
# Update mysql driver to ver 8.x 
#
# RUN \
#  && wget https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-8.0.20.tar.gz \
#  && tar -xf mysql-connector-java-8.0.20.tar.gz \
#  && mv ./mysql-connector-java-8.0.20/mysql-connector-java-8.0.20.jar /usr/share/logstash/mysql-connector-java.jar  \
#  && rm -rf ./mysql-connector-java-8.0.20 \
#  && rm mysql-connector-java-8.0.20.tar.gz

ARG MYSQL_CONNECT_VER
RUN echo $ELK_VERSION 
RUN echo "${MYSQL_CONNECT_VER}"
RUN echo $MYSQL_CONNECT_VER

RUN pwd ; wget https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-"${MYSQL_CONNECT_VER}".tar.gz  
RUN ls -la
RUN tar -xf mysql-connector-java-"${MYSQL_CONNECT_VER}".tar.gz 
RUN mv ./mysql-connector-java-"${MYSQL_CONNECT_VER}"/mysql-connector-java-"${MYSQL_CONNECT_VER}".jar /usr/share/logstash/mysql-connector-java.jar  
RUN rm -rf ./mysql-connector-java-"${MYSQL_CONNECT_VER}" 
RUN rm mysql-connector-java-"${MYSQL_CONNECT_VER}".tar.gz

