version: "3.6"
services:
  deb:
    hostname: isup2cron26.local
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env    
    volumes:
      - ./:/code
      - /etc/localtime:/etc/localtime:ro
    # entrypoint: /code/entrypoint.sh  
    command: /code/entrypoint.sh  
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "19"
    restart: always

