pipeline:

  build_image:
    image: docker:17.09.0-ce
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      docker build -t symmetricds .
    when:
      event: [pull_request, tag]

  push_image_to_quay:
    image: docker:17.09.0-ce
    secrets:
      - docker_quay_password
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
      - DOCKER_IMAGE=symmetricds
      - DOCKER_REPO=quay.io
      - DOCKER_BASEDIR=/ukhomeofficedigital/
      - DOCKER_USERNAME=ukhomeofficedigital+symmetricds
    commands:
      - docker login -u="$${DOCKER_USERNAME}" -p="$${DOCKER_QUAY_PASSWORD}" "$${DOCKER_REPO}"
      - ./publish.sh "symmetricds" "$${DOCKER_REPO}$${DOCKER_BASEDIR}$${DOCKER_IMAGE}" "$${DRONE_TAG}"
    when:
      event: tag
