version: "3"
services:
  target:
    image: postgres
    environment:
      - POSTGRES_USER=target
      - POSTGRES_PASSWORD=target
      - POSTGRES_DB=target
    ports:
      - "5432:5432"
  symds_target:
    build:
      context: .
    environment:
      - HTTPS=FALSE
      - GROUP_ID=target
      - DB_HOST=target
      - DB_SSL=FALSE
      - DB_TYPE=postgres
      - DB_NAME=target
      - DB_USER=target
      - DB_PASS=target
      - SYNC_URL=http://symds_target:31415/sync/target
      - REGISTRATION_URL=http://symds_source:31415/sync/source
    ports:
      - "31425:31415"
      - "31427:31417"
  symds_source:
    build:
      context: .
    environment:
      - HTTPS=FALSE
      - GROUP_ID=source
      - DB_HOST=source
      - DB_SSL=FALSE
      - DB_TYPE=mysql
      - DB_NAME=source
      - DB_USER=root
      - DB_PASS=source
      - SYNC_URL=http://symds_source:31415/sync/source
      - REPLICATE_TO=target
      - REPLICATE_TABLES=test
    ports:
      - "18080:8080"
      - "31415:31415"
      - "31417:31417"
  source:
    image: mysql:5.6
    # build:
    #   context: mysql-source
    environment:
      - MYSQL_USER=source
      - MYSQL_PASSWORD=source
      - MYSQL_ROOT_PASSWORD=source
      - MYSQL_DATABASE=source
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql-source/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
 
  adminer:
    # connect with something like 10.4.1.228:14117/  use compose service name or ip:port for server while logging in.
    image: adminer:4.7
    restart: always
    ports:
      - 14119:8080
  
