#!/usr/bin/env bash
cd ; date ; set +vx  ; set -vx ; # echo off, then echo on
set +vx
echo ~----------~----------Startinga [dirname $0 basename $0] `dirname "$0"`/`basename "$0"` 
echo ~----------~----------Startingd $HOSTNAME, pwd: `pwd`, dlr0: "$0", bashsource0: "${BASH_SOURCE[0]}", $(date +"%Y-%m-%d_%H.%M.%S")


#set -vx



function forarray()  
{
patrn=''

EXAMPLE_array=( 
10.4.1.231
10.4.1.224
)

array01=( 
192.168.88.36
192.168.88.45
)


#username
u=albe
p=22 # port

echo ; echo if this asks for a password, then install the ssh key to that host so it will no longer need the password.... ; echo;


date
for patrn in "${array01[@]}"
do
  echo "Processing $patrn ..."
  # take action on each $patrn 
  ssh $u@$patrn "echo hello; exit;"
  date
done 
}

forarray


