#!/usr/bin/env bash



echo ; echo Purpose:   shutdown list of linux VM''s ... ; echo;



date ; set +vx  ; set -vx ; # echo off, then echo on
set +vx
echo ~----------~----------Startinga [dirname $0 basename $0] `dirname "$0"`/`basename "$0"` 
echo ~----------~----------Startingd $HOSTNAME, pwd: `pwd`, dlr0: "$0", bashsource0: "${BASH_SOURCE[0]}", $(date +"%Y-%m-%d_%H.%M.%S")

source ./.env

# uncomment this to see commands and passwords.
# set -vx


function forarray()  
{
patrn=''

EXAMPLE_array=( 
10.4.1.231
10.4.1.224
192.168.88.64
)

array01=( 
192.168.88.36
192.168.88.45
)

#username
u=albe
p=22 # port

date; echo

for patrn in "${array01[@]}"
do
  echo "Processing $patrn ..."
  # take action on each $patrn 
  sshpass -p$supass  ssh -tt -o StrictHostKeyChecking=no  $u@$patrn  "echo $supass | sudo -S -s /bin/bash -c  'shutdown -h now; exit;'"
  date; echo
done 
}

forarray

