version: "3.6"

services:

  jupyter01:
    image: "jupyter/notebook"
    restart: on-failure
    volumes:
      - .:/notebooks
    ports:
      - "14123:8888"


# docker run --rm -it -p 8888:8888 -v "$(pwd):/notebooks" jupyter/notebook 

