

#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
#@  
#@  David Gleba
#@  
#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@   2021-07-02[Jul-Fri]13-29PM 

pup:
	 docker-compose -f docker-compose-prod.yml up

nuke:
	docker-compose   -f docker-compose-prod.yml  down -v  --rmi all --remove-orphans

down:
	docker-compose  -f docker-compose-prod.yml  down



#=================================================





