version: "3.6"
services:
  debs:
    # image: python:3.7
    hostname: cron24.local
    build:
      context: .
      dockerfile: ./Dockerfile
    # working_dir: /app
    volumes:
      - ./:/code
    # the tail command below simply keeps the container running so it does not exit.
    # command: bash -c "tail -f /dev/null"
    # command: bash -c "./cron.sh"
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "3"
    # restart: always
    # ports:
    #   - 8000:8000
    # environment:
    #   PYTHONUNBUFFERED: 1

