version: "3.6"
services:

  sym:
    build:
      context: .
    environment:
      - HTTPS=FALSE
      - GROUP_ID=source
      - DB_HOST=source
      - DB_SSL=FALSE
      - DB_TYPE=mysql
      - DB_NAME=source
      - DB_USER=root
      - DB_PASS=source
      - SYNC_URL=http://symds_source:31415/sync/source
      - REPLICATE_TO=target
      - REPLICATE_TABLES=test
    expose: [8080,31415,31417]  
    ports:
      # - "18080:8080"
      - "31415:31415"
      # - "31417:31417"
    volumes:
      - ./engines/:/app/syms/engines
      - ./datasys/:/app/syms/db
      - ./conf/:/app/conf
    #entrypoint: /app/conf/entry.sh 
    #
    # command: tail -f /app/symmetric-server/logs/symmetric.log
    # command: bash -c "tail -f /dev/null" 
    # command: /app/syms/bin/sym 
    command: /app/conf/entry.sh  
